### ISSUE TITLE
Integer comparison compilation warning

### ISSUE THREAD

**Issue by RobertKomara** [dselivanov/reco#5]
## Issue: compilation warning

Hi there and thanks for the interesting package. I have been using it quite a bit and wouldn't mind helping out if I can.  I am getting this compilation warning:

utils.cpp:43:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(q.size() < k){
                   ^

```{r install}
githubinstall::gh_install_packages("reco", ask = FALSE, force=TRUE)
```
Show in New WindowClear OutputExpand/Collapse Output
Downloading GitHub repo dselivanov/reco@master
from URL https://api.github.com/repos/dselivanov/reco/zipball/master
Installing reco
"C:/PROGRA1/MICROS1/ROPEN1/R-341.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/****/AppData/Local/Temp/RtmpyKsknU/devtools22d8bd227b1/dselivanov-reco-4058c0d" --library="C:/R_Packages"  \
  --install-tests 

* installing *source* package 'reco' ...
** libs
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA1/MICROS1/ROPEN1/R-341.0/include" -DNDEBUG  -I"C:/R_Packages/Rcpp/include" -I"C:/R_Packages/RcppArmadillo/include"   -I"C:/swarm/workspace/External-R-3.3.3/vendor/extsoft/include"  -fopenmp -DARMA_64BIT_WORD -DARMA_DONT_USE_OPENMP   -O2 -Wall  -mtune=native -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA1/MICROS1/ROPEN1/R-341.0/include" -DNDEBUG  -I"C:/R_Packages/Rcpp/include" -I"C:/R_Packages/RcppArmadillo/include"   -I"C:/swarm/workspace/External-R-3.3.3/vendor/extsoft/include"  -fopenmp -DARMA_64BIT_WORD -DARMA_DONT_USE_OPENMP   -O2 -Wall  -mtune=native -c als_implicit_core_solver.cpp -o als_implicit_core_solver.o
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA1/MICROS1/ROPEN1/R-341.0/include" -DNDEBUG  -I"C:/R_Packages/Rcpp/include" -I"C:/R_Packages/RcppArmadillo/include"   -I"C:/swarm/workspace/External-R-3.3.3/vendor/extsoft/include"  -fopenmp -DARMA_64BIT_WORD -DARMA_DONT_USE_OPENMP   -O2 -Wall  -mtune=native -c utils.cpp -o utils.o
utils.cpp: In function 'Rcpp::IntegerMatrix dotprod_top_k(const mat&, const mat&, int, int, Rcpp::Nullable<const arma::SpMat<double> >&)':
utils.cpp:43:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(q.size() < k){
                   ^
c:/Rtools/mingw_64/bin/g++ -m64 -shared -s -static-libgcc -o reco.dll tmp.def RcppExports.o als_implicit_core_solver.o utils.o -fopenmp -fopenmp -LC:/PROGRA1/MICROS1/ROPEN1/R-341.0/bin/x64 -lRlapack -LC:/PROGRA1/MICROS1/ROPEN1/R-341.0/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/swarm/workspace/External-R-3.3.3/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.3.3/vendor/extsoft/lib -LC:/PROGRA1/MICROS1/ROPEN1/R-341.0/bin/x64 -lR
installing to C:/R_Packages/reco/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (reco)

## SessionInfo

```{r session}
sessionInfo()
```

R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] httr_1.2.1          compiler_3.4.0      R6_2.2.0            RevoUtils_10.0.4    tools_3.4.0         withr_2.0.0        
 [7] yaml_2.1.14         curl_2.6            githubinstall_0.2.1 memoise_1.1.0       knitr_1.15.1        data.table_1.10.4  
[13] git2r_0.18.0        jsonlite_1.4        digest_0.6.12       devtools_1.12.0    

Is there any testing that I could help out with to run this warning down or is this a 'quick' fix by recasting the variable type to match? Also, I am happy to offer some typo/spelling fixes in documentation and code comments if you would be willing to accept them. Cheers!

**Comment by dselivanov** [comment]
Thanks for reporting. Should be fixed now. Could you check?

**Comment by RobertKomara** [comment]
I confirm that fixes the warning. Thanks!

**Comment by dselivanov** [comment]
@RobertKomara sorry I missed last paragraph. Any help is very appreciated. I'm planning to add some data and write tests for most of the functionality. I will ping you. Thanks!
